[theme]
name = "solarized-dark"

[icons]
name = "material-nf"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "none"

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
on_click = "nnotify disk /home"
unit = "GB"
interval = 60
warning = 20.0
alert = 10.0
format = "{icon}{available}"

[[block]]
block = "networkmanager"
on_click = "nnotify wlan"
ap_format = "{ssid^10}"
device_format = "{icon}{ap}"

[[block]]
block = "sound"
format = "{volume}"
max_vol = 100
show_volume_when_muted = true

[[block]]
block = "battery"
driver = "upower"
on_click = "nnotify batw"
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 5
on_click = "nnotify time"
format = "%a %d/%m %R"
