[theme]
name = "native"

[icons]
name = "awesome"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "none"


[[block]]
block = "cpu"
interval = 5
format = "{utilization} {frequency}"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}min,{max}max,{average}avg"
chip = "*-isa-*"
inputs = ["CPUTIN", "SYSTIN"]

[[block]]
block = "networkmanager"
on_click = "nnotify eth"
device_format = "{icon}"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
on_click = "nnotify disk /"
unit = "GB"
interval = 60
warning = 20.0
alert = 10.0
format = "{icon} {available}"

[[block]]
block = "sound"
format = "{volume}"
max_vol = 100
show_volume_when_muted = true
step_width = 1

[[block]]
block = "time"
interval = 5
on_click = "nnotify time"
format = "%a %d/%m %R"
