[theme]
theme = "native"

[icons]
icons = "awesome5"


[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:50) |"
short = " $title.str(max_w:10) |"

[[block]]
block = "cpu"
interval = 1
format_alt = " $icon $barchart $utilization "
format = " $icon $frequency{ $boost|} "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "temperature"
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "*-isa-*"

[[block]]
block = "net"
format = " $icon $device "
[[block.click]]
button = "left"
cmd = "nnotify eth"
update = true

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 60
warning = 20.0
alert = 10.0
format = " $icon $available "
format_alt = " $icon $available / $total "
[[block.click]]
button = "left"
cmd = "nnotify disk /"
update = true
[[block.click]]
button = "right"
action = "toggle_format"
update = true

[[block]]
block = "sound"
format = " $icon  {$volume.eng(w:2)|} "
show_volume_when_muted = true
max_vol = 100
step_width = 1

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%a %d/%m %R') "
[[block.click]]
button = "left"
cmd = "nnotify time"
update = true
