#!/bin/sh
# Luke's i3resize for sway
# Modified logic to be more consistent with floating and tiling

[ -z "$1" ] && echo "No direction provided" && exit 1
distanceStr="10 px or 2 ppt"

moveChoice() {
  swaymsg resize "$1" "$2" "$distanceStr" || swaymsg resize "$3" "$4" "$distanceStr"
}

case $1 in
  up)
    moveChoice shrink down grow up
    ;;
  down)
    moveChoice grow down shrink up
    ;;
  left)
    moveChoice shrink right grow left
    ;;
  right)
    moveChoice grow right shrink left
    ;;
esac

