#!/bin/sh

# Different terminals have different ways to spawn with classnames, so...
case "$TERMINAL" in
	urxvt*)
		$TERMINAL -name floater -e $@ ;;
	alacritty)
		if [ "$*" ]
		then
			$TERMINAL --class=floater -e $SHELL -i -c "$*"
		else
			$TERMINAL --class=floater
		fi ;;
	*)
		$TERMINAL -n floater -g 120x34 -e $@ ;;
esac
