#!/bin/sh

xbacklight -get > $HOME/.cache/currbacklight

xidlehook \
	--not-when-audio --not-when-fullscreen \
	--timer 300 \
		'xbacklight -get > $HOME/.cache/currbacklight; xbacklight -set 1' \
		'xbacklight -set "$(cat $HOME/.cache/currbacklight)"' \
	--timer 30 \
		'xbacklight -set "$(cat $HOME/.cache/currbacklight)"; betterlockscreen -l dim' \
		''
