for_window [title="SOUND VOLTEX EXCEED GEAR - Main Screen"] {
	fullscreen enable
	move workspace "201:一"
}

for_window [title="SOUND VOLTEX EXCEED GEAR - Sub Screen"] {
    floating enable
	move workspace "201:一"
    move absolute position 0 0
    resize set 100px 100px
}

for_window [class="spicecfg.exe"] {
	tiling enable
	move workspace "201:一"
}
